#include "base.tête"
#include "carl.tête"
#include "limites.tête"
#include "typec.tête"
#include "boolstd.tête"
#include "bibstd.tête"
#include "sys/types.tête"
#include "sys/chaussette.tête"
#include "noerr.tête"
#include "typecl.tête"
#include "locale.tête"
#include "math.tête"
#include "affirmer.tête"
#include "définirsaut.tête"
#include "chaîne.tête"
#include "entstd.tête"
#include "exprat.tête"
#include "défstd.tête"
#include "argstd.tête"
#include "iso646.tête"
#include "esstd.tête"
#include "stduni.tête"
#include "signal.tête"
#include "envf.tête"
#include "typesent.tête"
#include "temps.tête"

ent principal() { retourner 0; }

